name: IPAID

options:
  bundleIdPrefix: com.shplash
  deploymentTarget:
    iOS: "15.0"

packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19

targets:
  IPAID:
    type: application
    platform: iOS
    deploymentTarget: "15.0"

    sources:
      - App

    dependencies:
      - package: ZIPFoundation

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.shplash.ipaid
      PRODUCT_NAME: IPAID
      INFOPLIST_FILE: App/Info.plist
      SWIFT_VERSION: 5.0
      CURRENT_PROJECT_VERSION: 111
      MARKETING_VERSION: 1.1.1

    info:
      path: App/Info.plist
      properties:
        CFBundleShortVersionString: "1.1.1"
        CFBundleVersion: "111"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

    scheme:
      gatherCoverageData: false
      testTargets: []